name: tunetogether
description: "TuneTogether is a social media player app that allows users to stream and watch videos or listen to music together in real-time."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # local packages
  responsive_layout:
    path: packages/responsive_layout

  # State management and dependency injection
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6

  # Connect to databases
  http: ^1.2.1
  sqflite: ^2.3.3+1
  floor: any
  path: ^1.9.0
  path_provider: ^2.1.3
  uuid: ^4.4.0

  # # Firebase
  # firebase_auth: ^5.3.1
  # firebase_core: ^3.6.0
  # cloud_firestore: ^5.4.4
  # firebase_storage: ^12.3.3
  # firebase_messaging: ^15.1.3

  # # Supabase
  # supabase_flutter: ^2.8.0

  # Secrets
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1

  awesome_notifications: ^0.10.0
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  pinput: ^5.0.0
  logger: ^2.3.0
  country_picker: ^2.0.26
  dotted_border: ^2.1.0

  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svg/
    - assets/illustrations/
    - assets/app_logo/

# APP ICON
flutter_icons:
  image_path: assets/app_logo/tune_together_logo.png
  android: "launcher_icon"
  ios: "AppIcon"
  remove_alpha_ios: true
  min_sdk_ios: 21
